###
POST http://localhost:8080/api/projects/1/check


### create job
POST http://183.66.65.207:38080/api/pipeline
Content-Type: application/json

{
  "name": "test6",
  "yaml": "version: 1.0\nname: my-test2\nstages:\n  git-clone:\n    steps:\n      - name: git-clone\n        uses: git-checkout\n        with:\n          url: https://gitee.com/mohaijiang/spring-boot-example.git\n          branch: master\n  code-compile:\n    needs:\n      - git-clone\n    steps:\n      - name: code-compile\n        runs-on: maven:3.5-jdk-8\n        run: |\n          mvn clean package -Dmaven.test.skip=true\n      - name: save artifactory\n        use: hamster-artifactory\n        with:\n          name: some.zip\n          path: target/*.jar\n  build-image:\n    needs:\n      - code-compile\n    steps:\n      - run: |\n          docker build -t mohaijiang/spring-boot-example:latest .\n"
}

### update pipeline job
PUT http://localhost:8080/pipeline/test3?oldName=test3
Content-Type: application/json

{
  "newName": "test2",
  "yaml": "version: \"1.0\"\nname: test2\nstages:\n  git-clone:\n    steps:\n      - name: git-clone\n        uses: git-checkout\n        with:\n          url: https://gitee.com/mohaijiang/spring-boot-example.git\n          branch: master"
}

### exec job
POST http://183.66.65.207:38080/api/pipeline/test2/exec
Content-Type: application/json

### re exec job
POST http://localhost:8080/api/pipeline/maven/7/re-exec

### get pipeline job
GET http://localhost:8080/pipeline/test3

### delete pipeline job
DELETE http://localhost:8080/pipeline/test2

### get pipeline job details
GET http://localhost:8080/pipeline/test2/details?page=1&size=10


### get pipeline job detail
GET http://localhost:8080/pipeline/test2/detail/0


### get pipelie job log
GET http://localhost:8080/pipeline/test2/logs/0

### delete pipelie detail
DELETE http://localhost:8080/pipeline/test2/detail/0

### exec job
POST http://localhost:8080/pipeline/test3/exec
Content-Type: application/json

### cancel job
POST http://localhost:8080/pipeline/test3/7/stop

###
GET http://localhost:8080/pipeline/test3/logs/9

###
GET http://localhost:8080/api/pipeline/template/4



###
POST http://hamsternet.io/docs/abcd1234
Content-Type: application/json

{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}


### template category
GET http://localhost:8080/api/templates-category?type=1

### query workflow by project id
GET http://localhost:8080/api/projects/1/workflows

###
GET http://localhost:8080/api/workflows/1

### query contract by workflow detail id
GET http://localhost:8080/api/workflows/1/detail/1/contract

###query report by workflow detail id
GET http://localhost:8080/api/workflows/1/detail/2/report

### query contract by version and project id
GET http://localhost:8080/api/projects/1/contract/1.0

### query contract deploy detail
GET http://localhost:8080/api/projects/1/contract/deploy/detail

### query projects
GET http://localhost:8080/api/projects

### create projects
POST http://localhost:8080/api/projects
Content-Type: application/json

{
  "name": "lisi",
  "type": 1,
  "templateOwner": "jian-guo-s",
  "templateRepo": "polkadot",
  "frameType": 1,
  "repoOwner": "jian-guo-s",
  "userId": 53070354
}


### update project
PUT http://localhost:8080/api/projects/2
Content-Type: application/json

{
  "name": "wangwu",
  "userId": 53070354
}


### query project detail
GET http://localhost:8080/api/projects/2


### query project detail
DELETE http://localhost:8080/api/projects/2


### check name
POST http://localhost:8080/api/projects/check-name
Content-Type: application/json
access_token: q/fHsUxk/A9wemCoULUhgxKg+4xt1VgaWysR/G7H0tpEmwKLCa/8O9ukwHKcvqr2

{
  "owner": "jian-guo-s",
  "name": "ll"
}


