### 创建项目
POST http://localhost:8080/api/projects
Content-Type: application/json
Access-Token: ZHLIsR7EZjgwkE7z0Pco/pp1db7YfjJ/NUg/4YKTXD0FYXhHLiicYiQzL4yoJ2J/

{
  "name":"my-contract-Erc913",
  "type":1,
  "templateOwner":"hamster-template",
  "frameType":1,
  "deployType":1,
  "repoOwner":"jian-guo-s",
  "templateRepo":"ERC4907",
  "userId":53070354,
  "templateUrl":"https://github.com/hamster-contract/ERC4907.git"
}

### template
GET http://61.172.179.6:30302/api/templates/show?type=1&languageType=5&deployType=1
Content-Type: application/json
Access-Token: KjOkymfHU5cTOqiWlFQim1/jfTbVUx/llPle9MJh8x7ORooKyB48MyzqzWNeAJjg



### 执行检查
POST http://localhost:8080/api/projects/575054f4-1538-41ed-9d31-a17b4151f7b7/check
Content-Type: application/json
Access-Token: KjOkymfHU5cTOqiWlFQim1/jfTbVUx/llPle9MJh8x7ORooKyB48MyzqzWNeAJjg/

### 执行构建
POST http://localhost:8080/api/projects/2edddac6-d6b0-4f67-b9ad-94ff576c0e97/build
Content-Type: application/json
Access-Token: KjOkymfHU5cTOqiWlFQim1/jfTbVUx/llPle9MJh8x7ORooKyB48MyzqzWNeAJjg/


### create job
POST http://183.66.65.207:38080/api/pipeline
Content-Type: application/json

{
  "name": "test6",
  "yaml": "version: 1.0\nname: my-test2\nstages:\n  git-clone:\n    steps:\n      - name: git-clone\n        uses: git-checkout\n        with:\n          url: https://gitee.com/mohaijiang/spring-boot-example.git\n          branch: master\n  code-compile:\n    needs:\n      - git-clone\n    steps:\n      - name: code-compile\n        runs-on: maven:3.5-jdk-8\n        run: |\n          mvn clean package -Dmaven.test.skip=true\n      - name: save artifactory\n        use: hamster-artifactory\n        with:\n          name: some.zip\n          path: target/*.jar\n  build-image:\n    needs:\n      - code-compile\n    steps:\n      - run: |\n          docker build -t mohaijiang/spring-boot-example:latest .\n"
}

### update pipeline job
PUT http://localhost:8080/pipeline/test3?oldName=test3
Content-Type: application/json

{
  "newName": "test2",
  "yaml": "version: \"1.0\"\nname: test2\nstages:\n  git-clone:\n    steps:\n      - name: git-clone\n        uses: git-checkout\n        with:\n          url: https://gitee.com/mohaijiang/spring-boot-example.git\n          branch: master"
}

### exec job
POST http://183.66.65.207:38080/api/pipeline/test2/exec
Content-Type: application/json

### re exec job
POST http://localhost:8080/api/pipeline/maven/7/re-exec

### get pipeline job
GET http://localhost:8080/pipeline/test3

### delete pipeline job
DELETE http://localhost:8080/pipeline/test2

### get pipeline job details
GET http://localhost:8080/pipeline/test2/details?page=1&size=10


### get pipeline job detail
GET http://localhost:8080/pipeline/test2/detail/0


### get pipelie job log
GET http://localhost:8080/pipeline/test2/logs/0

### delete pipelie detail
DELETE http://localhost:8080/pipeline/test2/detail/0

### exec job
POST http://localhost:8080/pipeline/test3/exec
Content-Type: application/json

### cancel job
POST http://localhost:8080/pipeline/test3/7/stop

###
GET http://localhost:8080/pipeline/test3/logs/9

###
GET http://localhost:8080/api/pipeline/template/4



###
POST http://hamsternet.io/docs/abcd1234
Content-Type: application/json

{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}






### template category
GET http://localhost:8080/api/templates-category?type=1

### query templates
GET http://61.172.179.6:30302/api/templates-category/5/templates?languageType=0
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

### query template detail
GET http://localhost:8080/api/templates/1

### query projects
GET http://61.172.179.6:30302/api/projects?page=1&size=10
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

### query project detail
GET http://localhost:8080/api/projects/d67f12e7-6151-44f2-bfaf-ed84b188b92a
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

### build
POST http://localhost:8080/api/projects/d3586e4f-41a3-4d51-b91e-5a108d5dc53d/build
Content-Type: application/json
Access-Token: AklbPE0z2N7p38NiUvdUZIrTBpWNtdwA5a5pMXZMWmTgjVJxQwZ6a9541HKDBIdL


### check
POST http://localhost:8080/api/projects/d3586e4f-41a3-4d51-b91e-5a108d5dc53d/check
Content-Type: application/json
Access-Token: AklbPE0z2N7p38NiUvdUZIrTBpWNtdwA5a5pMXZMWmTgjVJxQwZ6a9541HKDBIdL


### query workflow by project id
GET http://localhost:8080/api/projects/4/workflows

### query workflow detail
GET http://localhost:8080/api/workflows/2/detail/3

###
GET http://localhost:8080/api/workflows/1

### query contract by workflow detail id
GET http://localhost:8080/api/workflows/1/detail/1/contract

###query report by workflow detail id
GET http://localhost:8080/api/workflows/1/detail/2/report

### query contract by version and project id
GET http://localhost:8080/api/projects/1/contract/1.0

### query contract deploy detail
GET http://localhost:8080/api/projects/1/contract/deploy/detail

### create projects
POST http://localhost:8080/api/projects
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

{
  "name": "k8s-data-47",
  "type": 2,
  "frameType": 1,
  "templateUrl": "https://github.com/hamster-template/vuejs.git",
  "deployType": 2,
  "templateRepo": "vuejs",
  "repoOwner": "jian-guo-s",
  "userId": 53070354
}



### check project
POST http://localhost:8080/api/projects/a5d11dfe-bd0a-4234-ac15-05a55b841721/check
Content-Type: application/json
Access-Token: AklbPE0z2N7p38NiUvdUZIrTBpWNtdwA5a5pMXZMWmTgjVJxQwZ6a9541HKDBIdL


### update project
PUT http://localhost:8080/api/projects/2
Content-Type: application/json

{
  "name": "wangwu",
  "userId": 53070354
}


### delete project
DELETE http://localhost:8080/api/projects/48068104-d96a-4d4d-a107-4fe3e268408f


### check name
POST http://localhost:8080/api/projects/check-name
Content-Type: application/json
Access-Token: q/fHsUxk/A9wemCoULUhgxKg+4xt1VgaWysR/G7H0tpEmwKLCa/8O9ukwHKcvqr2

{
  "owner": "jian-guo-s",
  "name": "ll"
}


###login with github
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "code": "4e8c16f53af4dafc459d",
  "clientId": "93512ec1db0460ada779"
}

###auth repo
POST http://localhost:8080/api/repo/authorization
Content-Type: application/json

{
  "code": "826a8fb7127374b39240",
  "clientId": "93512ec1db0460ada779",
  "userId": 53070354
}

### get version list
GET http://localhost:8080/api/projects/4/versions

### get workflow detail logs
GET http://localhost:8080/api/workflows/8/detail/9/logs

### query log by stage name
GET http://localhost:8080/api/workflows/8/detail/10/logs/code-compile


###query project contract
GET http://localhost:8080/api/projects/4/contract

###query contract name
GET http://localhost:8080/api/projects/4/contract/name

###query network
GET http://localhost:8080/api/projects/4/contract/network

####
GET http://34.232.105.81:8080/api/projects/3/contract

####
DELETE http://localhost:8080/api/projects/4/workflows/7


####
POST http://localhost:8080/api/projects/4/contract/deploy
Content-Type: application/json

{
  "contractId": 3,
  "projectId": 4,
  "version": "0",
  "network": "Goerli",
  "address": "xxxxxxxxxxxxxxxxxx"
}



#### create project by code
POST http://localhost:8080/api/projects/code
Content-Type: application/json
Access-Token: SkI5MW1BsDPrujDCUrRQdPbqUvuqwxxQupoppc+32RN9mUNl0E2SCTBieGENPVFL

{
  "name": "ERC721CommunityStream-25",
  "type": 1,
  "frameType": 1,
  "repoOwner": "guo-sun",
  "fileName": "test-sol",
  "content": "// SPDX-License-Identifier: MIT\npragma solidity >=0.4.21 <0.7.0;\n\nlibrary ConvertLib {\n    function convert(uint amount,uint conversionRate) public pure returns (uint convertedAmount) {\n        return amount * conversionRate;\n    }\n}"
}

#### query frontend deploy detail
GET http://localhost:8080/api/workflows/84/detail/80/frontend/deploy/detail
Content-Type: application/json
Access-Token: 8Bu8jYklS+53N/DYhS5LxnpcTqr3c9yeDYUdn49EA05Azw6LMMJUZe8+ppoxjMjs


#### delete workflow
DELETE http://localhost:8080/api/workflows/84/detail/80/deploy
Content-Type: application/json
Access-Token: 8Bu8jYklS+53N/DYhS5LxnpcTqr3c9yeDYUdn49EA05Azw6LMMJUZe8+ppoxjMjs


### UPDATE contract Deploy
POST http://localhost:8080/api/projects/9df7f308-80c1-4293-b802-8820499be125/contract/deploy
Content-Type: application/json
Access-Token: 57QEeUaskUR4UkiXxCCXsyUVZ1QHIQuEK4sy/CeOc+JBWMdgJoSuDM/aND9lePgE

{
  "contractId": 44,
  "id": "9df7f308-80c1-4293-b802-8820499be125",
  "projectId": "9df7f308-80c1-4293-b802-8820499be125",
  "version": "1",
  "network": "Testnet",
  "declareTxHash": "0x68430771ac16e2d6dc214e957b9dcdfccc6f16c7d86dd536c883a4f66702af1",
  "deployTxHash": "",
  "status": 1,
  "address": "",
  "type": 4
}

### create projects
POST http://localhost:8080/api/projects
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

{
  "name": "k8s-data-49",
  "type": 2,
  "frameType": 1,
  "templateUrl": "https://github.com/hamster-template/vuejs.git",
  "deployType": 2,
  "templateRepo": "vuejs",
  "repoOwner": "jian-guo-s",
  "userId": 53070354
}


### build
POST http://localhost:8080/api/projects/7549e23a-f264-4f97-8289-4c23a08da817/build
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip


### container deploy
POST http://localhost:8080/api/projects/7549e23a-f264-4f97-8289-4c23a08da817/workflows/613/detail/622/container/deploy
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

{
  "containerPort": 80,
  "serviceProtocol": "TCP",
  "servicePort": 8087,
  "serviceTargetPort": 80
}

### query templates
GET http://localhost:8080/api/templates/show?type=1&languageType=1
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

####
POST http://61.172.179.6:30302/api/projects/3775dd75-5f25-42d6-9b44-303e8127fe10/container/deploy
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

{
  "containerPort": 80,
  "serviceProtocol": "TCP",
  "servicePort": 8086,
  "serviceTargetPort": 80
}

####
GET http://61.172.179.6:30302/api/projects/3775dd75-5f25-42d6-9b44-303e8127fe10/container/deploy
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

### 获取日志 step 本地测试
GET http://127.0.0.1:8088/api/workflows/910/detail/1101/logs/Initialization/git
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

### 获取日志 step
GET http://localhost:5173/api/workflows/910/detail/1101/logs/Initialization/git
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

### 获取日志 step 测试环境 2
GET http://localhost:5173/api/workflows/920/detail/1110/logs/Initialization/git-clone
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip


### 测试下载文件
GET http://127.0.0.1:8088/api/download
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip
Worker-Token: jl@127.0.0.1

{
  "path": "jobs/test/job-details-log/10009.log"
}

#### get aptos move toml params
GET http://127.0.0.1:8088/api/projects/02e5fe46-f2cd-4016-a824-37917744ca2a/params/aptos
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip


#### get aptos move toml params
GET http://127.0.0.1:8088/api/projects/2b53cbf2-0bc6-41d7-8b53-aaaf753b1f78/params/aptos
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip


#### update aptos move toml params
POST http://127.0.0.1:8088/api/projects/2b53cbf2-0bc6-41d7-8b53-aaaf753b1f78/params/aptos
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

{
  "params": [{
      "key": "token_vesting",
      "value": "abcdefg"
    }]
}

#### get aptos project needs params
GET http://127.0.0.1:8088/api/projects/02e5fe46-f2cd-4016-a824-37917744ca2a/is-needs-params/aptos
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

#### aptos build
GET http://127.0.0.1:8088/api/projects/02e5fe46-f2cd-4016-a824-37917744ca2a/aptos-build
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

#### update aptos move toml params
POST http://127.0.0.1:8088/api/projects/02e5fe46-f2cd-4016-a824-37917744ca2a/params/aptos
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

{
  "params": [{
      "key": "raffle",
      "value": "abcdefg"
    }]
}

### 创建项目
POST http://61.172.179.6:30302/api/projects
Content-Type: application/json
Access-Token: ZHLIsR7EZjgwkE7z0Pco/pp1db7YfjJ/NUg/4YKTXD0FYXhHLiicYiQzL4yoJ2J/

{
  "name":"my-contract-Erc917",
  "type":1,
  "templateOwner":"hamster-template",
  "frameType":1,
  "deployType":1,
  "repoOwner":"jian-guo-s",
  "templateRepo":"FunctionsConsumer",
  "userId":53070354,
  "templateUrl":"https://github.com/hamster-template/FunctionsConsumer.git"
}


#### get workflow check
GET http://61.172.179.6:30302/api/project/81be5991-f19c-4236-a11e-cfbb4c028cee/workflow/setting/check
Content-Type: application/json
Access-Token: ZHLIsR7EZjgwkE7z0Pco/pp1db7YfjJ/NUg/4YKTXD0FYXhHLiicYiQzL4yoJ2J/

### setting workflow
POST http://61.172.179.6:30302/api/project/81be5991-f19c-4236-a11e-cfbb4c028cee/workflow/setting
Content-Type: application/json
Access-Token: ZHLIsR7EZjgwkE7z0Pco/pp1db7YfjJ/NUg/4YKTXD0FYXhHLiicYiQzL4yoJ2J/


{
  "tool": ["MetaTrust (OSA)","eth-gas-reporter"]
}

### check project
POST http://61.172.179.6:30302/api/projects/81be5991-f19c-4236-a11e-cfbb4c028cee/check
Content-Type: application/json
Access-Token: ZHLIsR7EZjgwkE7z0Pco/pp1db7YfjJ/NUg/4YKTXD0FYXhHLiicYiQzL4yoJ2J/


###
GET http://61.172.179.6:30302/api/workflows/1979/detail/3161/report/overview
Content-Type: application/json
Access-Token: ZHLIsR7EZjgwkE7z0Pco/pp1db7YfjJ/NUg/4YKTXD0FYXhHLiicYiQzL4yoJ2J/

###
GET http://61.172.179.6:30302/api/report/2091
Content-Type: application/json
Access-Token: ZHLIsR7EZjgwkE7z0Pco/pp1db7YfjJ/NUg/4YKTXD0FYXhHLiicYiQzL4yoJ2J/