### 创建项目
POST http://localhost:8080/api/projects
Content-Type: application/json
Access-Token: pAckUATfeIsxSq1qzIVIdJcKf3jIhRDmnchfAqIrU2xX4smOe4Hd2p3e3iZNnX0/

{
  "name": "project-three",
  "type": 1,
  "templateOwner": "jian-guo-s",
  "templateRepo": "truffle-webpack",
  "frameType": 1,
  "repoOwner": "mohaijiang",
  "userId": 2
}

### 执行检查
POST http://localhost:8080/api/projects/7814b99f-3628-41ab-80fd-50fea5c6f7e8/check
Content-Type: application/json
Access-Token: AklbPE0z2N7p38NiUvdUZIrTBpWNtdwA5a5pMXZMWmTgjVJxQwZ6a9541HKDBIdL


### create job
POST http://183.66.65.207:38080/api/pipeline
Content-Type: application/json

{
  "name": "test6",
  "yaml": "version: 1.0\nname: my-test2\nstages:\n  git-clone:\n    steps:\n      - name: git-clone\n        uses: git-checkout\n        with:\n          url: https://gitee.com/mohaijiang/spring-boot-example.git\n          branch: master\n  code-compile:\n    needs:\n      - git-clone\n    steps:\n      - name: code-compile\n        runs-on: maven:3.5-jdk-8\n        run: |\n          mvn clean package -Dmaven.test.skip=true\n      - name: save artifactory\n        use: hamster-artifactory\n        with:\n          name: some.zip\n          path: target/*.jar\n  build-image:\n    needs:\n      - code-compile\n    steps:\n      - run: |\n          docker build -t mohaijiang/spring-boot-example:latest .\n"
}

### update pipeline job
PUT http://localhost:8080/pipeline/test3?oldName=test3
Content-Type: application/json

{
  "newName": "test2",
  "yaml": "version: \"1.0\"\nname: test2\nstages:\n  git-clone:\n    steps:\n      - name: git-clone\n        uses: git-checkout\n        with:\n          url: https://gitee.com/mohaijiang/spring-boot-example.git\n          branch: master"
}

### exec job
POST http://183.66.65.207:38080/api/pipeline/test2/exec
Content-Type: application/json

### re exec job
POST http://localhost:8080/api/pipeline/maven/7/re-exec

### get pipeline job
GET http://localhost:8080/pipeline/test3

### delete pipeline job
DELETE http://localhost:8080/pipeline/test2

### get pipeline job details
GET http://localhost:8080/pipeline/test2/details?page=1&size=10


### get pipeline job detail
GET http://localhost:8080/pipeline/test2/detail/0


### get pipelie job log
GET http://localhost:8080/pipeline/test2/logs/0

### delete pipelie detail
DELETE http://localhost:8080/pipeline/test2/detail/0

### exec job
POST http://localhost:8080/pipeline/test3/exec
Content-Type: application/json

### cancel job
POST http://localhost:8080/pipeline/test3/7/stop

###
GET http://localhost:8080/pipeline/test3/logs/9

###
GET http://localhost:8080/api/pipeline/template/4



###
POST http://hamsternet.io/docs/abcd1234
Content-Type: application/json

{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}






### template category
GET http://localhost:8080/api/templates-category?type=1

### query templates
GET http://34.232.105.81:8088/api/templates-category/1/templates?languageType=1
Content-Type: application/json
Access-Token: Aq7I04y2uh+0fWXjRq8V3MSIcBCvJMn/bILGq3xvJzFW1WcWxpjmExDMmbJoT6Qu

### query templates
GET http://34.232.105.81:8088/api/templates/show?type=1&languageType=4
Content-Type: application/json
Access-Token: Aq7I04y2uh+0fWXjRq8V3MSIcBCvJMn/bILGq3xvJzFW1WcWxpjmExDMmbJoT6Qu

### query template detail
GET http://localhost:8080/api/templates/1

### query projects
GET http://localhost:8080/api/projects?page=1&size=10
Content-Type: application/json
Access-Token: AklbPE0z2N7p38NiUvdUZIrTBpWNtdwA5a5pMXZMWmTgjVJxQwZ6a9541HKDBIdL

### query project detail
GET http://localhost:8080/api/projects/48068104-d96a-4d4d-a107-4fe3e268408f

### build
POST http://localhost:8080/api/projects/d3586e4f-41a3-4d51-b91e-5a108d5dc53d/build
Content-Type: application/json
Access-Token: AklbPE0z2N7p38NiUvdUZIrTBpWNtdwA5a5pMXZMWmTgjVJxQwZ6a9541HKDBIdL


### check
POST http://localhost:8080/api/projects/d3586e4f-41a3-4d51-b91e-5a108d5dc53d/check
Content-Type: application/json
Access-Token: AklbPE0z2N7p38NiUvdUZIrTBpWNtdwA5a5pMXZMWmTgjVJxQwZ6a9541HKDBIdL


### query workflow by project id
GET http://localhost:8080/api/projects/4/workflows

### query workflow detail
GET http://localhost:8080/api/workflows/2/detail/3

###
GET http://localhost:8080/api/workflows/1

### query contract by workflow detail id
GET http://localhost:8080/api/workflows/1/detail/1/contract

###query report by workflow detail id
GET http://localhost:8080/api/workflows/1/detail/2/report

### query contract by version and project id
GET http://localhost:8080/api/projects/1/contract/1.0

### query contract deploy detail
GET http://localhost:8080/api/projects/1/contract/deploy/detail

### create projects
POST http://localhost:8080/api/projects
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

{
  "name": "k8s-data-37",
  "type": 2,
  "frameType": 1,
  "templateUrl": "https://github.com/hamster-template/vuejs.git",
  "templateRepo": "vuejs",
  "repoOwner": "jian-guo-s",
  "userId": 53070354
}



### check project
POST http://localhost:8080/api/projects/a5d11dfe-bd0a-4234-ac15-05a55b841721/check
Content-Type: application/json
Access-Token: AklbPE0z2N7p38NiUvdUZIrTBpWNtdwA5a5pMXZMWmTgjVJxQwZ6a9541HKDBIdL


### update project
PUT http://localhost:8080/api/projects/2
Content-Type: application/json

{
  "name": "wangwu",
  "userId": 53070354
}


### delete project
DELETE http://localhost:8080/api/projects/48068104-d96a-4d4d-a107-4fe3e268408f


### check name
POST http://localhost:8080/api/projects/check-name
Content-Type: application/json
Access-Token: q/fHsUxk/A9wemCoULUhgxKg+4xt1VgaWysR/G7H0tpEmwKLCa/8O9ukwHKcvqr2

{
  "owner": "jian-guo-s",
  "name": "ll"
}


###login with github
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "code": "4e8c16f53af4dafc459d",
  "clientId": "93512ec1db0460ada779"
}

###auth repo
POST http://localhost:8080/api/repo/authorization
Content-Type: application/json

{
  "code": "826a8fb7127374b39240",
  "clientId": "93512ec1db0460ada779",
  "userId": 53070354
}

### get version list
GET http://localhost:8080/api/projects/4/versions

### get workflow detail logs
GET http://localhost:8080/api/workflows/8/detail/9/logs

### query log by stage name
GET http://localhost:8080/api/workflows/8/detail/10/logs/code-compile


###query project contract
GET http://localhost:8080/api/projects/4/contract

###query contract name
GET http://localhost:8080/api/projects/4/contract/name

###query network
GET http://localhost:8080/api/projects/4/contract/network

####
GET http://34.232.105.81:8080/api/projects/3/contract

####
DELETE http://localhost:8080/api/projects/4/workflows/7


####
POST http://localhost:8080/api/projects/4/contract/deploy
Content-Type: application/json

{
  "contractId": 3,
  "projectId": 4,
  "version": "0",
  "network": "Goerli",
  "address": "xxxxxxxxxxxxxxxxxx"
}



#### create project by code
POST http://localhost:8080/api/projects/code
Content-Type: application/json
Access-Token: SkI5MW1BsDPrujDCUrRQdPbqUvuqwxxQupoppc+32RN9mUNl0E2SCTBieGENPVFL

{
  "name": "ERC721CommunityStream-25",
  "type": 1,
  "frameType": 1,
  "repoOwner": "guo-sun",
  "fileName": "test-sol",
  "content": "// SPDX-License-Identifier: MIT\npragma solidity >=0.4.21 <0.7.0;\n\nlibrary ConvertLib {\n    function convert(uint amount,uint conversionRate) public pure returns (uint convertedAmount) {\n        return amount * conversionRate;\n    }\n}"
}

#### query frontend deploy detail
GET http://localhost:8080/api/workflows/84/detail/80/frontend/deploy/detail
Content-Type: application/json
Access-Token: 8Bu8jYklS+53N/DYhS5LxnpcTqr3c9yeDYUdn49EA05Azw6LMMJUZe8+ppoxjMjs


#### delete workflow
DELETE http://localhost:8080/api/workflows/84/detail/80/deploy
Content-Type: application/json
Access-Token: 8Bu8jYklS+53N/DYhS5LxnpcTqr3c9yeDYUdn49EA05Azw6LMMJUZe8+ppoxjMjs


### UPDATE contract Deploy
POST http://localhost:8080/api/projects/9df7f308-80c1-4293-b802-8820499be125/contract/deploy
Content-Type: application/json
Access-Token: 57QEeUaskUR4UkiXxCCXsyUVZ1QHIQuEK4sy/CeOc+JBWMdgJoSuDM/aND9lePgE

{
  "contractId": 44,
  "id": "9df7f308-80c1-4293-b802-8820499be125",
  "projectId": "9df7f308-80c1-4293-b802-8820499be125",
  "version": "1",
  "network": "Testnet",
  "declareTxHash": "0x68430771ac16e2d6dc214e957b9dcdfccc6f16c7d86dd536c883a4f66702af1",
  "deployTxHash": "",
  "status": 1,
  "address": "",
  "type": 4
}

### build
POST http://localhost:8080/api/projects/736d4714-142f-4323-9a9f-e2e496e5c594/build
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip


### container deploy
POST http://localhost:8080/api/projects/736d4714-142f-4323-9a9f-e2e496e5c594/workflows/353/detail/413/container/deploy
Content-Type: application/json
Access-Token: ufMizxtT9EqaTJf45pXUgUWget8C8jtbR+l/ltaerv/WYwyWAIUPOqRH/+f6R0ip

{
  "containers": "[{\"name\":\"jian-guo-s-test\",\"ports\":[{\"containerPort\":8082}],\"resources\":{}}]",
  "servicePorts": "[{\"protocol\":\"TCP\",\"port\":8082,\"targetPort\":8088,\"nodePort\":30318}]"
}