FROM debian:latest

RUN apt update &&\
    apt install -y -qq --no-install-recommends apt-transport-https ca-certificates curl git gnupg lsb-release;

RUN mkdir -m 0755 -p /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -

RUN echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update && \
    apt-get install -y -qq --no-install-recommends docker-ce-cli nodejs ;\
    rm -rf /var/lib/apt/lists/*
