FROM rust:1.73

WORKDIR /home

#Move-Lint install
RUN git clone https://github.com/BeosinBlockchainSecurity/Move-Lint.git
WORKDIR /home/Move-Lint/
RUN cargo build --release
RUN chmod a+x target/release/move-lint
ENV PATH "$PATH:/home/Move-Lint/target/release"

#docker buildx build -f ./Dockerfile_rust_tools -t hamstershare/rust-tools:1.73 --platform=linux/amd64 --push .
#docker buildx build -f ./Dockerfile_rust_tools -t hamstershare/rust-tools:1.73 --platform=linux/amd64,linux/arm64 --push .